//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KorisnickiInterfejs.WSBolnickiPodaci {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSBolnickiPodaci.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DajSvaOgranicenja", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DajSvaOgranicenja();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DajSvaOgranicenja", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> DajSvaOgranicenjaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DajMaxBrojUputaNaDan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DajMaxBrojUputaNaDan(string pomIDDoktora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DajMaxBrojUputaNaDan", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DajMaxBrojUputaNaDanAsync(string pomIDDoktora);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : KorisnickiInterfejs.WSBolnickiPodaci.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<KorisnickiInterfejs.WSBolnickiPodaci.Service1Soap>, KorisnickiInterfejs.WSBolnickiPodaci.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet DajSvaOgranicenja() {
            return base.Channel.DajSvaOgranicenja();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DajSvaOgranicenjaAsync() {
            return base.Channel.DajSvaOgranicenjaAsync();
        }
        
        public string DajMaxBrojUputaNaDan(string pomIDDoktora) {
            return base.Channel.DajMaxBrojUputaNaDan(pomIDDoktora);
        }
        
        public System.Threading.Tasks.Task<string> DajMaxBrojUputaNaDanAsync(string pomIDDoktora) {
            return base.Channel.DajMaxBrojUputaNaDanAsync(pomIDDoktora);
        }
    }
}
