//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoslovnaLogika.WSDoktori {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSDoktori.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DajSveDoktore", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DajSveDoktore();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DajSveDoktore", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> DajSveDoktoreAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DajDoktora", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DajDoktora(string jmbg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DajDoktora", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DajDoktoraAsync(string jmbg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DajJmbgDoktora", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DajJmbgDoktora(string ime, string prezime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DajJmbgDoktora", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DajJmbgDoktoraAsync(string ime, string prezime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : PoslovnaLogika.WSDoktori.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<PoslovnaLogika.WSDoktori.Service1Soap>, PoslovnaLogika.WSDoktori.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet DajSveDoktore() {
            return base.Channel.DajSveDoktore();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DajSveDoktoreAsync() {
            return base.Channel.DajSveDoktoreAsync();
        }
        
        public string DajDoktora(string jmbg) {
            return base.Channel.DajDoktora(jmbg);
        }
        
        public System.Threading.Tasks.Task<string> DajDoktoraAsync(string jmbg) {
            return base.Channel.DajDoktoraAsync(jmbg);
        }
        
        public string DajJmbgDoktora(string ime, string prezime) {
            return base.Channel.DajJmbgDoktora(ime, prezime);
        }
        
        public System.Threading.Tasks.Task<string> DajJmbgDoktoraAsync(string ime, string prezime) {
            return base.Channel.DajJmbgDoktoraAsync(ime, prezime);
        }
    }
}
